# Generated by Django 5.2.4 on 2025-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_updated_at_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
